import type { Assessment, AssessmentResult } from '../../domain/types/models';

const MOCK_ASSESSMENT_RESULTS: AssessmentResult[] = [
  {
    id: 'res-1',
    assessmentId: 'ass-1',
    finalScore: 85,
    category: 'A',
    criteriaScores: {
      c1_organizacion: 90,
      c2_nivel_servicio: 80,
      c3_recuperacion_costes: 85,
      c4_om: 90,
      c5_girh: 80,
      c6_rendicion_cuentas: 95,
      c7_conservacion: 85,
      c8_genero: 80,
      c9_autogestion: 85,
    },
  },
  {
    id: 'res-2',
    assessmentId: 'ass-2',
    finalScore: 68,
    category: 'B',
    criteriaScores: {
      c1_organizacion: 70,
      c2_nivel_servicio: 60,
      c3_recuperacion_costes: 65,
      c4_om: 75,
      c5_girh: 60,
      c6_rendicion_cuentas: 80,
      c7_conservacion: 70,
      c8_genero: 65,
      c9_autogestion: 70,
    },
  },
  {
    id: 'res-3',
    assessmentId: 'ass-3',
    finalScore: 52,
    category: 'C',
    criteriaScores: {
      c1_organizacion: 50,
      c2_nivel_servicio: 45,
      c3_recuperacion_costes: 55,
      c4_om: 50,
      c5_girh: 40,
      c6_rendicion_cuentas: 60,
      c7_conservacion: 55,
      c8_genero: 50,
      c9_autogestion: 60,
    },
  },
];

const MOCK_ASSESSMENTS: (Assessment & { result?: AssessmentResult })[] = [
  {
    id: 'ass-1',
    capsId: '1',
    surveyDate: '2025-03-15',
    surveyorName: 'Ana García',
    serviceLevel: {
      sourceType: 'MEJORADA',
      intakeLocation: 'DENTRO',
      fetchTime: 'MAX_30_MIN',
      waterAvailability: 'SIEMPRE',
      compliesWithEndowment: true,
      qualityPerception: { odor: 'BUENO', color: 'BUENO', flavor: 'BUENO' },
      bacteriologicalAnalysisDone: true,
      bacteriologicalAnalysisResult: 'NEGATIVO',
      otherTests: { arsenic: true, iron: false, turbidity: true, ph: true },
    },
    legalization: {
      municipalCertificate: true,
      inaaRegistration: true,
      rucNumber: true,
      differentiatedTariff: true,
      sapLegalization: true,
      hasAssemblyRecords: 'SI',
    },
    costRecovery: {
      hasTariff: true,
      tariffType: 'CONSUMO',
      hasBankAccount: true,
      hasSavingsForThreeMonths: true,
      morosityPercentage: 'LESS_5',
    },
    operationAndMaintenance: {
      hasOmPlan: true,
      executesOmPlan: true,
    },
    girh: {
      hygieneCampaigns: true,
      cleaningDays: true,
      recordsMonthlyFlow: true,
      informsWaterAvailability: true,
      adjustsDistribution: true,
      hasMicromeasurement: true,
      rechargeAreaIdentified: true,
      rechargeAreaCharacterized: true,
      rechargeAreaProtectionPlan: true,
      protectionPlanImplemented: true,
    },
    accountability: {
      informsEconomicStatus: true,
      monthlyAccountabilityToBoard: true,
      accountingBookUpdated: true,
      usersBookUpdated: true,
      minutesBookUpdated: true,
      morosityReported: true,
    },
    conservation: {
      mabe: {
        pumpingStation: {
          hasFence: true,
          noLatrinesNearby: true,
          goodConditionCaseta: true,
          lockedDoor: true,
          macroMeterRegistering: true,
        },
        storageTank: {
          hasFenceGoodCondition: true,
          noCracks: true,
          noLeaks: true,
          noOverflow: true,
          valvesGoodCondition: true,
          inspectionCoverGoodCondition: true,
        },
        chlorinationSystemWorking: true,
        noVisibleSystemLeaks: true,
      },
    },
    gender: { genderAdendum: true, genderActionsCompliance: true },
    result: MOCK_ASSESSMENT_RESULTS[0],
  },
  {
    id: 'ass-2',
    capsId: '2',
    surveyDate: '2025-01-10',
    surveyorName: 'Carlos Ruiz',
    // ... basic assessment data for mock
    serviceLevel: {
      sourceType: 'MEJORADA',
      intakeLocation: 'PATIO',
      fetchTime: 'MAX_30_MIN',
      waterAvailability: 'MAYOR_PARTE',
      compliesWithEndowment: true,
      qualityPerception: { odor: 'BUENO', color: 'BUENO', flavor: 'BUENO' },
      bacteriologicalAnalysisDone: true,
      bacteriologicalAnalysisResult: 'POSITIVO',
      otherTests: { arsenic: false, iron: false, turbidity: true, ph: true },
    },
    legalization: {
      municipalCertificate: true,
      inaaRegistration: false,
      rucNumber: false,
      differentiatedTariff: false,
      sapLegalization: true,
      hasAssemblyRecords: 'ALGUNAS',
    },
    costRecovery: {
      hasTariff: true,
      tariffType: 'PROMEDIO',
      hasBankAccount: false,
      hasSavingsForThreeMonths: true,
      morosityPercentage: '6_15',
    },
    operationAndMaintenance: { hasOmPlan: true, executesOmPlan: false },
    girh: {
      hygieneCampaigns: true,
      cleaningDays: true,
      recordsMonthlyFlow: false,
      informsWaterAvailability: true,
      adjustsDistribution: false,
      hasMicromeasurement: false,
      rechargeAreaIdentified: true,
      rechargeAreaCharacterized: false,
      rechargeAreaProtectionPlan: false,
      protectionPlanImplemented: false,
    },
    accountability: {
      informsEconomicStatus: true,
      monthlyAccountabilityToBoard: true,
      accountingBookUpdated: false,
      usersBookUpdated: true,
      minutesBookUpdated: true,
      morosityReported: true,
    },
    conservation: {
      mag: {
        intake: { hasFenceGoodCondition: true, noPollutionSources: true, noCracksInIntake: true },
        storageTank: {
          hasFenceGoodCondition: true,
          noCracksInTank: true,
          noLeaksInTank: true,
          noOverflow: true,
          valvesGoodCondition: true,
          inspectionCoverGoodCondition: true,
        },
        chlorinationSystemWorking: true,
        noVisibleSystemLeaks: true,
      },
    },
    gender: { genderAdendum: true, genderActionsCompliance: false },
    result: MOCK_ASSESSMENT_RESULTS[1],
  },
  {
    id: 'ass-3',
    capsId: '3',
    surveyDate: '2024-11-20',
    surveyorName: 'Ana García',
    serviceLevel: {
      sourceType: 'NO_MEJORADA',
      intakeLocation: 'PUBLICO',
      fetchTime: 'MORE_30_MIN',
      waterAvailability: 'VECES',
      compliesWithEndowment: false,
      qualityPerception: { odor: 'MALO', color: 'MALO', flavor: 'MALO' },
      bacteriologicalAnalysisDone: false,
      bacteriologicalAnalysisResult: 'NO_SABE',
      otherTests: { arsenic: false, iron: false, turbidity: false, ph: false },
    },
    legalization: {
      municipalCertificate: false,
      inaaRegistration: false,
      rucNumber: false,
      differentiatedTariff: false,
      sapLegalization: false,
      hasAssemblyRecords: 'NO',
    },
    costRecovery: {
      hasTariff: false,
      tariffType: 'NO_PAGAN',
      hasBankAccount: false,
      hasSavingsForThreeMonths: false,
      morosityPercentage: 'MORE_15',
    },
    operationAndMaintenance: { hasOmPlan: false, executesOmPlan: false },
    girh: {
      hygieneCampaigns: false,
      cleaningDays: false,
      recordsMonthlyFlow: false,
      informsWaterAvailability: false,
      adjustsDistribution: false,
      hasMicromeasurement: false,
      rechargeAreaIdentified: false,
      rechargeAreaCharacterized: false,
      rechargeAreaProtectionPlan: false,
      protectionPlanImplemented: false,
    },
    accountability: {
      informsEconomicStatus: false,
      monthlyAccountabilityToBoard: false,
      accountingBookUpdated: false,
      usersBookUpdated: false,
      minutesBookUpdated: false,
      morosityReported: false,
    },
    conservation: {
      well: {
        well: { hasFence: false, noLatrinesNearby: false },
        handPump: {
          ropeAndPistonsGoodCondition: false,
          metalStructureGoodCondition: false,
          pumpGuideGoodCondition: false,
          bearingsLeverAxlesGoodCondition: false,
          risingMainGoodCondition: false,
          noCracksInBase: false,
        },
        apron: { noCracksInCurbs: false, noCracksInApron: false },
        drainageChannel: { noObstructions: false, noCracksInChannel: false },
        soakPit: { gravelFilterGoodCondition: false, noSediments: false },
      },
    },
    gender: { genderAdendum: false, genderActionsCompliance: false },
    result: MOCK_ASSESSMENT_RESULTS[2],
  },
];

export const AssessmentService = {
  getAll: async (): Promise<(Assessment & { result?: AssessmentResult })[]> => {
    return MOCK_ASSESSMENTS;
  },
  getLatestByCapsId: async (
    capsId: string
  ): Promise<(Assessment & { result?: AssessmentResult }) | undefined> => {
    return MOCK_ASSESSMENTS.filter((a) => a.capsId === capsId).sort(
      (a, b) => new Date(b.surveyDate).getTime() - new Date(a.surveyDate).getTime()
    )[0];
  },
  getByCapsId: async (capsId: string): Promise<(Assessment & { result?: AssessmentResult })[]> => {
    return MOCK_ASSESSMENTS.filter((a) => a.capsId === capsId);
  },
};
